# AquaRelay configuration

network:
  bind:
    address: 0.0.0.0
    port: 19132

  backend:
    address: 127.0.0.1
    port: 19133

game-settings:
  session-timeout: 10
  debug-mode: false

  max-players: 50

  motd: "Â§bAquaRelay Proxy"
  sub-motd: "www.aquarelay.dev"