# AquaRelay configuration

network-settings:
  bind:
    address: 0.0.0.0
    port: 19132
  backend:
    address: 127.0.0.1
    port: 19133

  session-timeout: 10
  max-mtu: 1492

misc-settings:
  debug-mode: false
  log-name: proxy.log

game-settings:
  max-players: 50
  motd: "Â§bAquaRelay Proxy"
  sub-motd: "www.aquarelay.dev"